name: Tests

on:
  pull_request:
    branches: '*'

  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch, tag or SHA to release from'
        required: true
        default: 'main'

jobs:
  tests:
    name: Run tests for ${{ matrix.os }} for ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: python -m pip install -r requirements_test.txt
      - name: Install the current version
        run: python -m poetry install
      - name: Run test cases
        run: python -m pytest --verbose --cov
